=== jvaarala/XML_Schema_example/order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="order">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="billto"/>
                <xs:element ref="shipto"/>
                <xs:element ref="items"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="billto">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="address"/>
                <xs:element maxOccurs="unbounded" ref="phone"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="shipto">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="address"/>
                <xs:element ref="phone"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="item"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="itemid"/>
                <xs:element ref="quantity"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="itemid" type="xs:integer"/>
    <xs:element name="quantity" type="xs:integer"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="address" type="xs:string"/>
    <xs:element name="phone" type="xs:string"/>
</xs:schema>

=== jvaarala/XML_Schema_example/order.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<order id="234809A" xmlns="http://www.examplenamespace.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.examplenamespace.com order.xsd">
    <billto>
        <name>Liepa Roma</name>
        <address>514 Vale Street</address>
        <phone>515-758-8159</phone>
        <phone>937-294-5207</phone>
    </billto>
    <shipto>
        <name>Sigeberht Gulshan</name>
        <address>893 Glendale Road</address>
        <phone>619-863-0860</phone>
    </shipto>
    <items>
        <item>
            <itemid>257948</itemid>
            <quantity>12</quantity>
        </item>
        <item>
            <itemid>683047</itemid>
            <quantity>4</quantity>
        </item>
        <item>
            <itemid>982753</itemid>
            <quantity>1</quantity>
        </item>
    </items>
</order>
